### ISSUE TITLE
unclear method of usage

### ISSUE THREAD

**Issue by synesdeija** [aloutfi/bcwav#1]
Hello,
Would you mind adding instructions to this to allow use across skill levels? Documentation is fun!

**Comment by synesdeija** [comment]
Hi, I was hoping you wouldn't mind updating your README so that I might use this cute tool?

**Comment by aloutfi** [comment]
Thank you for the feedback. we've added this to our next sprint and will tag you for review. 🙂

**Comment by aloutfi** [comment]
Done in #2
